### ISSUE TITLE
Is Semantic UI still under active development?

### ISSUE THREAD

**Issue by TwoFistedJustice** [Semantic-UI-Vue/Semantic-UI-Vue#103]
I'm looking for a css framework to use with vue. I really like the way semantic ui looks, but it seems like it is no longer under active development.

1. What is the current situation with Semantic UI?

2. And how will that affect this Vue js adaptation of it?

**Comment by edjroot** [comment]
1. Semantic-Org/Semantic-UI#6109
2. Good question! (Disclaimer: I'm _not_ a maintainer.)

**Comment by mariolamacchia** [comment]
This repo is a component library *based* on Semantic UI. I do not contribute to Semantic UI, so I cannot answer your first answer, but the links that @edjroot posted should explanatory. 

> And how will that affect this Vue js adaptation of it?

This integration has the goal of implementing the js part of the latest Semantic UI version. If they keep working on it, we'll follow their changes, otherwise, it'll stay like it is now.

If you like how Semantic UI looks now, I don't see how the fact that the development on their side is slowing down would affect you.

**Comment by mariolamacchia** [comment]
I'm closing this. Will reopen later if necessary
