### ISSUE TITLE
lacking many component

### ISSUE THREAD

**Issue by johnzeus14** [Semantic-UI-Vue/Semantic-UI-Vue#151]
the semantic vue integration is lacking so many component compared to the real semantic ui..some which include a navbar and appropriate card component audio component, and image component ..you should check out vuetify also how do i contribute

**Comment by mariolamacchia** [comment]
We are quite aware of that.

Please understand the maintainers of this project (and most of the projects you find on Github) don't get paid and have already a full-time job. The developer of Vuetify is doing an amazing job

Unfortunately, these issues don't help us developing components, but make us more frustrated instead. Please, consider contributing instead of complaining.

**Comment by mariolamacchia** [comment]
We are quite aware of that.

Please understand the maintainers of this project (and most of the projects you find on Github) don't get paid and have already a full-time job.

Unfortunately, these issues don't help us developing components, but make us more frustrated instead. Please, consider contributing instead of complaining. You will find a [CONTRIBUTING](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) file containing all the info just for that.

**Comment by johnzeus14** [comment]
i am so sorry about that..to be honest you are doing a great Job..i love  semantic ui ...i love you guys , you have done a great job to bring it to vue js

**Comment by johnzeus14** [comment]
i also want to know to how i  can contribute... i am new vue js developer
