### ISSUE TITLE
Maybe .vue one file components?

### ISSUE THREAD

**Issue by outluch** [Semantic-UI-Vue/Semantic-UI-Vue#55]
Hi. I love the idea to mix semantic ui and vue. I even wanted to start that on my own after using it extensively with jquery vetsion wrapping in my own library in one project.
What are reasons to use JSX? Why not vue single file components?
One of reasons I dont use React - its JSX and beauty of vue template-script-style combo in .vue files.

**Comment by mariolamacchia** [comment]
Hi, that's a good question. 

FIrst of all, there is no need to use JSX in your project if you want to use this library. In fact, all the examples are in .vue files.

Like you, I also prefer how the Vue component file is structured over the React's JSX. However, in this case, there is no CSS to write (Semantic UI Vue is based on the official Semantic UI CSS) and most components are made of a single element, which means the `<tempate>` block will almost always contain a single line. On the other hand, JSX does offers a lot of flexibility.

I might consider replacing .jsx with .vue if a drawback comes up, but I don't see any so far.

**Comment by outluch** [comment]
For example, I, as one of fans of vue, would like to contribute to this repo. But I looked into sourcecode, saw JSX there and closed tab :D It is instinct. And what about classes, I already saw some classes from utils.js used in some components. I would like to see usual to vue `:class="{active: isActive, big: isBig}"` or even: `:class="{active, big}"`. It would be so cool to be in comfort zone of vueeeeee.
Thanks for quick answer, I will be waiting for +1s for my question :)

**Comment by mariolamacchia** [comment]
Sorry to hear you don't want to contribute. 

Again, the choice of JSX is for removing those 5ish lines of boilerplate code from each component. Apart from that, the rest of the file isn't different.

I do consider your feedback, but it's more about personal taste than other. I will reopen if I get any feedback concerning practical issues.

**Comment by spack971** [comment]
Hi,

I don't mind the JSX but Vue.js comes out of the box with Single File Components so I find it better to make use of Vue.js technology.

Would you allow patches to move components from JSX files to VUE files?

That's something I would definitely like to work on.

**Comment by mariolamacchia** [comment]
Vue.js doesn't come out of the box with either .jsx or .vue support, you need a webpack loader in any case. I am using an [official loader](https://github.com/vuejs/babel-plugin-transform-vue-jsx), so I am pretty sure using jsx with vue is not discouraged.

**Comment by spack971** [comment]
I'm just trying to say that according to the [documentation](https://vuejs.org/v2/guide/render-function.html) although JSX is an option, "Vue recommends using templates to build your HTML in the vast majority of cases".

And [template files](https://vuejs.org/v2/guide/syntax.html) are valid HTML that can be loaded in any recent browser with no need for extra software.

I just think that using template files will make it easier for people  with a Vue background to contribute.

**Comment by mariolamacchia** [comment]
> I'm just trying to say that according to the documentation although JSX is an option, "Vue recommends using templates to build your HTML in the vast majority of cases".

True, they do say that. However, our case doesn't fall into the vast majority: every component has no CSS and two lines of HTML at most. 

As I said before, the alternative to JSX is using render functions in plain JS, since we do not need 2/3 of what the Vue file provides and it would only add a lot of noise to the code. [As the documentation says](https://vuejs.org/v2/guide/render-function.html#JSX), JSX is meant to reduce the pain of writing render functions in plain js. 

> And template files are valid HTML that can be loaded in any recent browser with no need for extra software.

The template part of a .vue file cannot be loaded into any browser: it needs a Webpack loader to be transformed into a javascript string, that is then [compiled to a render function](https://vuejs.org/v2/guide/render-function.html#Template-Compilation).

> I just think that using template files will make it easier for people with a Vue background to contribute.

Not sure about this. AFAIK, Vuetify is the biggest component library for Vue: although [they do not use Vue files](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VBtn/VBtn.js), they have 6k+ stars and 135+ PRs opened within last month.

I think the community is attracted by features more than by Vue/JSX files 🙂
