### ISSUE TITLE
How do I hook rating events?

### ISSUE THREAD

**Issue by gmask** [Semantic-UI-Vue/Semantic-UI-Vue#66]
Hello, thanks for making this. So far it has been quite helpful.

I am wondering how I can access `@click` events for the `<sui-rating>` component? That is, how can I use the clicked rating with axios or whatever?

**Comment by tesarwijaya** [comment]
you can hook events using `.native` modifier in your case, it should be `@click.native`. i have submitting PR regarding this issue but still waiting for the review.

**Comment by gmask** [comment]
Thanks, that did the trick. Can I get a sanity check? Here's how I'm using ratings currently, but I'm not sure if there's a cleaner way:

**In my template**:
```
<sui-rating :rating="currentRating" ref="suiRating" @click.native="storeRating"></sui-rating>
```

**Methods**:
```
storeRating() {
    let newRating = this.$refs.suiRating.selected;
    this.currentRating = newRating;

    axios.post(route('ratings.store', this.entry.id), {
        rating: newRating
    }).then((response) => {
        //
    })
},
```

I guess I just want to know if there's a better way than calling `this.$refs.suiRating`? Also what about half-stars? I see that even [the original Semantic UI rating](https://semantic-ui.com/modules/rating.html) doesn't support them, but any idea how difficult it would be to implement?

**Comment by mariolamacchia** [comment]
Hey @gmask! I've just updated it so that rating is passed to the event. If you update to version 0.1.1 it should work straight away. Example here: https://semantic-ui-vue.github.io/#/modules/rating

Regarding the half-stars, there is an [open issue](https://github.com/Semantic-Org/Semantic-UI/issues/1048) on SemanticUI: we can implement it here once they do it there 🙂 

I'll close this, let me know if you have any issue.
