### ISSUE TITLE
Create Item component

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#9]
Here is the original one: https://semantic-ui.com/views/item.html.

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by Double-A-92** [comment]
I'm trying this.

Btw does anybody if there are any nomenclatures for the components? E.g. I saw that the "comments" class became the CommentGroup component. Should I do the same with "items" -> "ItemGroup" ? And are there more such rules written somewhere?

**Comment by mariolamacchia** [comment]
I'm trying to stick as much as possible to the [react version](https://react.semantic-ui.com/introduction): when in doubt, you can compare the props and the components to that one. So, yes, `ItemGroup` :)

**Comment by Double-A-92** [comment]
What about things like "middle aligned content" ? The react version made a prop out og the "middle aligned" part called verticalAlign.  But to me that seems like general semantic classes that don't really belong to the content.  I'm not even sure if the content class is an Item specific thing, since e.g. Card and others also have one...

What would you do?

**Comment by mariolamacchia** [comment]
Right. In that case, you'll probably want to create a directive, [`sui-floated`](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/src/directives/floated.js) is a valid example. ATM, however, other components have vertical align as prop: if you want to do the same here don't worry about that, we can take care of it in a separate issue.
